---
# zabbix64-proxy from offical repos only supports MySQL:
#
# 30432:20240729:154101.802 [Z3001] connection to database
# '/var/db/zabbix/zabbix_proxy.db' failed:
# [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
#
# For sqlite use own package at pkg.in.meissner.it!
#
# Upgrade of sqlite database is not possible - just remove it
# rm /var/db/zabbix/zabbix_proxy.db

# zabbix_server_pkg_name_prefix will be set in mit.zabbix-server.common

- name: Set defaults
  ansible.builtin.set_fact:
    zabbix_proxy_db_dir: /var/db/zabbix
    zabbix_proxy_conf_dir2: /usr/local/etc/{{ zabbix_server_pkg_name_prefix }}
    zabbix_proxy_confd_dir: /usr/local/etc/{{ zabbix_server_pkg_name_prefix }}/zabbix_proxy.conf.d
    zabbix_proxy_conf_file: /usr/local/etc/{{ zabbix_server_pkg_name_prefix }}/zabbix_proxy.conf
    zabbix_proxy_service_name: zabbix_proxy

- name: Install zabbix-proxy
  ansible.builtin.package:
    name: "{{ zabbix_server_pkg_name_prefix }}-proxy"
  notify: Restart zabbix-proxy
