---
# mit-ansible-install-package-from-apt-source 2025-01-28
# 2023-10-12: Initial version
# 2024-09-18: Cosmetic updates (ansible-lint)
# 2024-09-19: Added handler "apt-package-has-been-changed"
# 2025-01-11: Cosmetic updates (Removed ansible-lint warnings)
# 2025-01-28: Cosmetic updates (Removed ansible-lint warnings)

- name: Set defaults
  ansible.builtin.set_fact:
    apt_keyrings: /etc/apt/keyrings
    # used for filenames
    visible_name: zabbix-official-repo
- name: Set defaults
  ansible.builtin.set_fact:
    local_apt_key: "{{ apt_keyrings }}/{{ visible_name }}.gpg"
- name: Set defaults
  ansible.builtin.set_fact:
    apt_package: zabbix-proxy-sqlite3=1:{{ zabbix_server_version }}{{ "+" + zabbix_distribution_release if (ansible_distribution=='Ubuntu') }}
    apt_source_list_name: local-{{ visible_name }}.list
    apt_repository: deb [signed-by={{ local_apt_key }}]
                    https://repo.zabbix.com/zabbix/{{ zabbix_server_major_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    gpg_key_src: https://repo.zabbix.com/zabbix-official-repo.key

# No need to change anything beyond this line

- name: Create {{ apt_keyrings }}
  ansible.builtin.file:
    path: "{{ apt_keyrings }}"
    state: directory
    mode: '755'
- name: Install gpg
  ansible.builtin.apt:
    pkg: gpg
- name: Add apt gpg key # noqa: risky-shell-pipe command-instead-of-module
  ansible.builtin.shell: wget -q -O - {{ gpg_key_src }} | gpg --dearmor > {{ local_apt_key }}
  args:
    creates: "{{ local_apt_key }}"
  environment: "{{ proxy_env }}"
- name: Enable apt repository
  ansible.builtin.apt_repository:
    repo: "{{ apt_repository }}"
    state: present
  changed_when: false
- name: Install {{ apt_package }}
  ansible.builtin.apt:
    name: "{{ apt_package }}"
    update_cache: true
    state: present
  notify: apt-package-has-been-changed
- name: Deactivate apt repository
  ansible.builtin.apt_repository:
    repo: "{{ apt_repository }}"
    state: absent
  changed_when: false
- name: Remove /etc/apt/sources.list.d/{{ apt_source_list_name }}
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ apt_source_list_name }}
    state: absent
- name: Add {{ apt_source_list_name }}.disabled # noqa name[template]
  ansible.builtin.template:
    src: local-apt.list
    dest: /etc/apt/sources.list.d/{{ apt_source_list_name }}.disabled
    mode: '644'
  changed_when: false
